### ISSUE TITLE
Implement sample app for minting NFTs in Aptos

### ISSUE THREAD

**Issue by victorges** [livepeer/studio-sample-app#69]
- Upload video assets, store assets at IPFS, edit the metadata according to ERC-721 standards or Aptos metadata standards (TBD)
 - Should allow users to mint without specifying a contract — minting to a common contract is okay for sample application purposes
 - Should allow video minted to be played back using the Livepeer Player
 - Should return a contract address and a Token ID (JSON metadata blob on IPFS)
 - Should be on it’s own dedicated domain (optional)

**Comment by Shih-Yu** [comment]
Started a simple layout where page connect to Petra wallet an d can upload asset to Studio using SDK
https://github.com/livepeer/Aptos-NFT-Dapp

**Comment by victorges** [comment]
Where is this deployed? 👀

**Comment by Shih-Yu** [comment]
Getting Eric to add to to vercel
